### ISSUE TITLE
create main page with menu (play and settings buttons)

### ISSUE THREAD

**Issue by Ekaterina1994** [Ekaterina1994/quiz#11]
Add menu with navigation. In the menu must be 2 buttons - "Start" (to Quiz) and "Settings". At the top left side must be a button "Main" (to main page).

**Comment by Ekaterina1994** [comment]
Главное — добавить страницу с меню и страницу с настройками (пкстую), по которым можно навигироваться. Если вы знаете про семантический HTML, то в курсе, что для навигации кнопки не супер). В задачу входит прикручивани react-router, это основное.

**Comment by Ekaterina1994** [comment]
Maybe something is already finish but check it please: 

1. Set up Linter (if it possible) so that props are formatted in the same way: if there is one prop, then all in one line, if there are several props, then each prop on a new line.
2. Get rid of nesting as much as possible - for example, it is better to format routes in one line, rather than breaking the code into 7 lines.
3. Remove Materialize from the project and use only your own styles (we will use css, module.scss)
4. Comments for the code are formatted in the same way:
```
/*
 * comments
 */
 ```
5. Transfer such elements as lists, headings, pieces of text, etc. into separate components.
6. Is there an extra nesting in the Menu.tsx file? There is both a nav and a div with a wrapper class and a ul. Better to delete unneeded nesting.
7. Where immutable strings are used (for example, in routes, etc.) it is better to use constants. They can be used with curly braces:
```
const ROUTE = "dfjsoifjseoghsgeso"
...
<Route path={ROUTE} element={<SettingsPage />}  />
```

**Comment by tritonJS826** [comment]
Not done

**Comment by Ekaterina1994** [comment]
1. Remove unnecessary styles for the button, check to use mixins? and variables
2. Think - do you need a layout? can it be added immediately to the file with routes?
3. 3 pages: on the main window in the center (against the background of the rainbow at the request of Victor - a joke) where there are two link buttons - settings and play; the settings are still an empty page, and the page with the quiz) So that you can navigate through the page, the header will remain - as I understand it. As it is now.
4. Do not use synonyms in naming - make the same names of some elements everywhere
5. Rename type Props. Check that naming is normal everywhere. It is possible to use an interface rather than a type in a List file
6. Set paths to start from the root (src/...)
7. Add classNames into constants

**Comment by tritonJS826** [comment]
done
