### ISSUE TITLE
make RULES.md 

### ISSUE THREAD

**Issue by Ekaterina1994** [Ekaterina1994/quiz#13]

**Comment by Ekaterina1994** [comment]
- [x] 1. Revise the wording of paragraph 1 in the document (add what to specify when naming a branch)
- [x] 2. Delete paragraph 4
- [x] 3. In paragraph 5, describe when the definition of done is executed, those when the task is considered completed
- [x] 4. In 6 paragraph reformulate phrase (into numbered lists)
- [x] 5. In 7 paragraph delete $git commit -m
- [x] 6. In DOCUMENTATION part, change the wording in the client folder (e.g. readme in subfolders)
- [x] 7. In DOCUMENTATION part to correct the structure (flew off) and read about the constants
- [x] 8. In CODE part, instead of 1 paragraph, describe what is the conf file if it contains all the rules for code formatting
- [x] 9. Reformulate about when which consts we use 
- [x] 10. All commits with start with BIG letter
- [x] 11. Add types of comments the cat is used in the code, indicate where and when which type is used (JSDoc and other)
- [x] 12. Info about components, move the description to the README, which describes the modules and what they consist of
- [x] 13. About variables - normally formulate an example
- [x] 14. Add convention that all code with comments on English

**Comment by tritonJS826** [comment]
not done

**Comment by skif-cezar** [comment]
1. Add brunch naming convention.
2. In the GIT part - fix the commit message example (add curly braces) + remove "a commit command".
3. In the GIT part, move the items about tasks to the COMMUNICATION part or create a new section "Project Management".
4. Make code examples in one format - multiline.
5. In the CODE part, change the item about magic values ​​- make it more concise.
6. In the CODE part, delete rule 1 - about the linter.
7. Add interface and type naming convention.
8. Check compliance with conventions in the projectю

**Comment by skif-cezar** [comment]
- [x] 1.  In the GIT part - fix the commit message example (add curly braces) + remove "a commit command".
- [x] 2.  In the GIT part, move the items about tasks to the COMMUNICATION part or create a new section "Project Management".
- [x] 3.  Make code examples in one format - multiline.
- [x] 4.  In the CODE part, change the item about magic values ​​- make it more concise.
- [x] 5.  In the CODE part, delete rule 1 - about the linter.

**Comment by tritonJS826** [comment]
done
