### ISSUE TITLE
Recreate components

### ISSUE THREAD

**Issue by tritonJS826** [Ekaterina1994/quiz#17]

**Comment by skif-cezar** [comment]
- [x] 1. Rename the file containing the main button to Main or use the Button component (maybe the menu is the start + settings button and not the header).
- [x] 2. Parse and write to the chat, what is the difference between the menu and the main button.
- [x] 3. Delete List component.
- [x] 4. Check the button component - it's not currently used anywhere.

**Comment by tritonJS826** [comment]
done
