### ISSUE TITLE
Make good README.md

### ISSUE THREAD

**Issue by Ekaterina1994** [Ekaterina1994/quiz#3]

**Comment by tritonJS826** [comment]
Describe main project goal, main modules, instructions how to start, build and deploy your modules etc. Investigate a little this subject

**Comment by Ekaterina1994** [comment]
Task is done. Please make review. Should I add something else  or delete?

**Comment by tritonJS826** [comment]
Not done, fix problems

**Comment by tritonJS826** [comment]
Add a link to the YouTube channel to playlist with your project overview. Add link to your CV and link edin.

**Comment by Ekaterina1994** [comment]
Done.

**Comment by tritonJS826** [comment]
Not done

**Comment by Ekaterina1994** [comment]
1. Change description of project (there need to delete last sentence about I want learn technologies)
2. Change main goal of project to something like "make quiz for people for fun and play". Non need deep philosophy
3. Change description of module structure (for example, we have 2 modules client and doc. client contain this ans that. Docs contain this). Add description about what is inside components, logic and other folders

**Comment by tritonJS826** [comment]
done
