### ISSUE TITLE
make a good structure for project

### ISSUE THREAD

**Issue by Ekaterina1994** [Ekaterina1994/quiz#5]

**Comment by tritonJS826** [comment]
Basic example: https://github.com/tritonJS826/sooner-or-later-2d/tree/master

**Comment by tritonJS826** [comment]
Structure could be better

**Comment by tritonJS826** [comment]
Not done

**Comment by Ekaterina1994** [comment]
1. Delete folder modules. File put into components
2. Make file Questions easier (split into parts, move functions to other files) - use custom hooks?
3. Add folders for every component in folder components
4. Rename folders in logic (folder names based on the main file)
5. Think about - we need layout or not. If need then why and maybe we can use it in file with routes
6. Delete folder Score

**Comment by tritonJS826** [comment]
not done

**Comment by skif-cezar** [comment]
- [x] 1. Move IQuestionDTO to the model folder or create a separate folder for DTO models.
- [x] 2. Change structure (remove models from services).
- [x] 3. Check if all files are in the correct folders.
- [x] 4. Reconsider where (in which file) it is better to put constants with paths for routes. (for example, from main can put in a quizpage? From App, transfer constants with paths to those files where these paths go).

**Comment by tritonJS826** [comment]
done
