### ISSUE TITLE
create services

### ISSUE THREAD

**Issue by Ekaterina1994** [Ekaterina1994/quiz#6]

**Comment by tritonJS826** [comment]
Which services?

**Comment by tritonJS826** [comment]
not done. Services is not created.

**Comment by Ekaterina1994** [comment]
Done

**Comment by tritonJS826** [comment]
Not done

**Comment by Ekaterina1994** [comment]
1. Create models from type in services (create new file)
2. Remove redundant code in services
3.  Use fetch for get data

**Comment by tritonJS826** [comment]
not done

**Comment by skif-cezar** [comment]
- [x] 1. Edit QuizService is now a copy of the stub version and doesn't work as it should.
- [x] 2. Rename the class QuizRound by the name of the file.
- [x] 3. Change data name in QuizServiceStub and similar.
- [x] 4. See if the path variable is needed after the closing curly braces in the questions variable (QuizServiceStub file).

**Comment by tritonJS826** [comment]
done
