### ISSUE TITLE
remove unnecessary code

### ISSUE THREAD

**Issue by Ekaterina1994** [Ekaterina1994/quiz#8]

**Comment by Ekaterina1994** [comment]
Cleaned code. Deleted code for authorization and files with info about users.

**Comment by tritonJS826** [comment]
not done. create .gitignore and add in .gitignore node_modules, and other mess files like build folder and other

**Comment by Ekaterina1994** [comment]
Done. Problem: I didn't find full info about what should be in the .gitignore. I just saw articles with recommendations but there wasn't  good examples. Also I read about global gitignore. But I'm not sure that I need it for this project.

**Comment by tritonJS826** [comment]
not done

**Comment by Ekaterina1994** [comment]
Finish task. Deleted unused files in rot folder and useless comments in files.

**Comment by tritonJS826** [comment]
Not done

**Comment by Ekaterina1994** [comment]
1. Move all constants outside the function
2. No need to write typing everywhere (but how then to avoid errors from the linter? Or remove this rule too?)
3. It’s normal to figure out what it means "/". Maybe we don’t need it, if we need to justify
4. Disable destructuring rule in eslint
5. Remove redundant files with routes
6. Remove replace from route
7. Delete useless comments - wtrite only important
8. Delete unneeded dependencies in package.json

**Comment by tritonJS826** [comment]
not done

**Comment by Ekaterina1994** [comment]
1. Delete dependencies we don't use in the package.json  (p.28)
2. Delete repeated scripts (p. 29)

**Comment by tritonJS826** [comment]
done
